### ISSUE TITLE
Bug: Cant set subduction scaling relation

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#107]
using the 

### 1 TMG_SUB_2017

setting **TMG_SUB_2017** , recalc=true raises....

```
: org.opensha.commons.exceptions.InvalidRangeException: Rake angle should be either within (45, 135) for interface or (-45, -135) for inslab-normal events
        at org.opensha.commons.calc.magScalingRelations.magScalingRelImpl.TMG2017SubMagAreaRel.setRake(TMG2017SubMagAreaRel.java:147)
        at scratch.UCERF3.enumTreeBranches.ScalingRelationships$8.getMag(ScalingRelationships.java:273)
        at nz.cri.gns.NZSHM22.opensha.enumTreeBranches.NZSHM22_ScalingRelationshipNode.getMag(NZSHM22_ScalingRelationshipNode.java:76)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemRuptSet.recalcMags(NZSHM22_InversionFaultSystemRuptSet.java:151)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_SubductionInversionRunner.setRuptureSetFile(NZSHM22_SubductionInversionRunner.java:63)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.setRuptureSetFile(NZSHM22_AbstractInversionRunner.java:268)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### 2 without setting scaling relation

```
: java.lang.NullPointerException
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.validateConfig(NZSHM22_AbstractInversionRunner.java:385)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:404)
        at nz.cri.gns.NZSHM22.opensha.util.NZSHM22_PythonGateway$CachedSubductionInversionRunner.runInversion(NZSHM22_PythonGateway.java:334)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

### 3 SMPL_NZ_INT_MN

+ recalc=true

```
py4j.protocol.Py4JJavaError: An error occurred while calling o0.runInversion.
: java.lang.IllegalStateException: Regime type of rupture set and scaling relationship do not match.
        at com.google.common.base.Preconditions.checkState(Preconditions.java:508)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.validateConfig(NZSHM22_AbstractInversionRunner.java:391)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:404)
        at nz.cri.gns.NZSHM22.opensha.util.NZSHM22_PythonGateway$CachedSubductionInversionRunner.runInversion(NZSHM22_PythonGateway.java:334)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by voj** [comment]
1. This is caused by us assigning a rake of 0 to subduction sections on fault model load. Now that we pass rake into the ScalingRelationship when calculating magnitude, a rake of 0 is flagged as illegal for subduction sections. My preferred solution is to re-create rupture sets. I can also write a fix that sets rake to 90 if we have to be able to use old subduction rupture sets.
2. For pre-modular rupture sets, a scaling relationship must be set in the config.
3. I will create a PR for this.
