### ISSUE TITLE
RuntimeException: Problem Mmax: 6.8500000000000005 Braemar

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#119]
java.lang.RuntimeException: Problem Mmax: 6.8500000000000005  Braemar, Subsection 0
        at nz.cri.gns.NZSHM22.opensha.analysis.NZSHM22_FaultSystemRupSetCalc.getCharSubSeismoOnFaultMFD_forEachSection(NZSHM22_FaultSystemRupSetCalc.java:120)

##  config:
```
{
  "job_args": {
    "worker_pool_size": 1,
    "jvm_heap_max": 30,
    "java_threads": 16,
    "use_api": true,
    "general_task_id": "",
    "mock_mode": false
  },
  "general_args": {
    "unique_id": "RVYU",
    "subtask_type": "INVERSION",
    "model_type": "CRUSTAL",
    "file_id": "RmlsZToxNTg3LjBuVm9GdA==",
    "task_title": "Build Seed Inversions TEST",
    "task_description": " - for Chris DiCaprio\n - using replica of QXV0b21hdGlvblRhc2s6NTcyNkI1OFNo setttings."
   },
  "task_args": {
    "rounds": [
      0
    ],
    "completion_energies": [
      0.0
    ],
    "max_inversion_times": [
      5, 15, 30, 60
    ],
    "mfd_transition_mags": [
      7.85
    ],
    "mfd_equality_weights": [
      "1e4"
    ],
    "mfd_inequality_weights": [
      "0"
    ],
    "slip_rate_weighting_types": [
      "BOTH"
    ],
    "slip_rate_normalized_weights": [
      "1e4"
    ],
    "slip_rate_unnormalized_weights": [
      "1e5"
    ],
    "selection_interval_secs": [
      1
    ],
    "threads_per_selector": [
      4
    ],
    "averaging_threads": [
      4
    ],
    "averaging_interval_secs": [
      30
    ],
    "non_negativity_function": [
      "TRY_ZERO_RATES_OFTEN"
    ],
    "perturbation_function": [
      "EXPONENTIAL_SCALE"
    ],
    "slip_rate_weights": [
      0
    ],
    "slip_uncertainty_scaling_factors": [
      2
    ],
    "seismogenic_min_mags": [
      7.0
    ],
    "mfd_mag_gt_5_sans": [
      4.2
    ],
    "mfd_mag_gt_5_tvz": [
      0.9
    ],
    "mfd_b_values_sans": [
      0.9
    ],
    "mfd_b_values_tvz": [
      1.2
    ],
    "scaling_relationships": [
      "SIMPLE_CRUSTAL"
    ],
    "scaling_recalc_mags": [
      true
    ],
    "deformation_models": [
      "FAULT_MODEL"
    ],
    "paleo_rate_constraint_weights": [
      0
    ],
    "paleo_rate_constraints": [
      "GEOLOGIC_SLIP_1_0"
    ],
    "paleo_probability_models": [
      "UCERF3_PLUS_PT5"
    ],
    "paleo_parent_rate_smoothness_constraint_weights": [
      0
    ],
    "scaling_c_val_dip_slips": [
      "4.2"
    ],
    "scaling_c_val_strike_slips": [
      "4.2"
    ]
  }
}
```

```
Traceback (most recent call last):
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/runzi/execute/inversion_solution_builder_task.py", line 273, in <module>
    task.run(**config)
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/runzi/execute/inversion_solution_builder_task.py", line 167, in run
    inversion_runner.runInversion()
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o1.runInversion.
: java.lang.RuntimeException: Problem Mmax: 6.8500000000000005  Braemar, Subsection 0
        at nz.cri.gns.NZSHM22.opensha.analysis.NZSHM22_FaultSystemRupSetCalc.getCharSubSeismoOnFaultMFD_forEachSection(NZSHM22_FaultSystemRupSetCalc.java:120)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs$RegionalTargetMFDs.init(NZSHM22_CrustalInversionTargetMFDs.java:203)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs$RegionalTargetMFDs.<init>(NZSHM22_CrustalInversionTargetMFDs.java:118)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs.init(NZSHM22_CrustalInversionTargetMFDs.java:263)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs.<init>(NZSHM22_CrustalInversionTargetMFDs.java:85)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionConfiguration.forModel(NZSHM22_CrustalInversionConfiguration.java:172)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.configure(NZSHM22_CrustalInversionRunner.java:147)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.configure(NZSHM22_CrustalInversionRunner.java:24)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:425)
        at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.runInversion(NZSHM22_CrustalInversionRunner.java:191)
        at nz.cri.gns.NZSHM22.opensha.util.NZSHM22_PythonGateway$CachedCrustalInversionRunner.runInversion(NZSHM22_PythonGateway.java:299)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by chrisbc** [comment]
**RESOLVED** with workaround. MinMags now requires bin-centred values, so use **6.95 instead of 7.0**.!
