### ISSUE TITLE
Feature: Refactor Subduction Inversions to use new opensha modular branch

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#20]
**The SRM Team want to** start using new opensha features implemented in the opensha/modular-fault-sys-rup-set2 branch

**so we can** explore in-flight inversion averaging techniques, pertubation optimisations and the new reporting codebase and outputs.

**Done when:**
 - [x] Adapt NZSHM Inversion Config, Generator and TargetMFD class (and any other essential changes) to suit new codebase
 - [x] Run an Inversion on a **Subduction Rupture set**: [RmlsZTo1MzcwLjA5andhYw==](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/FileDetail/RmlsZTo1MzcwLjA5andhYw==)
 - [x] Run same Inversion via Gateway API.

**Comment by chrisbc** [comment]
Current test output:

```Done with Inversion after 10 mins 0.1 secs.
Rounds: 60
Total Iterations: 332657725
Total Perturbations: 277453
Best energy:
	Total:	1.3054032E7	Equality:	1.3054032E7	Entropy:	0.0
	Inequality:	0.0	SlipRate:	929291.2	RateMinimize:	0.0
	MFDEquality:	1.212474E7	MFDInquality:	0.0
Final energies:
	MFD Equality: 1.212474E7
	Slip Rate: 929291.2
	Rupture Rate Minimization: 0.0
	MFD Inequality: 0.0
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel$Tapered' to: Tapered Slip Along Rupture
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel' to: Tapered Slip Along Rupture
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule$ModelBased' to: Rupture Average Slips
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule' to: Rupture Average Slips
Rupture Set:	Mapping module type 'scratch.UCERF3.logicTree.U3LogicTreeBranch' to: Logic Tree Branch
Rupture Set:	Mapping module type 'org.opensha.commons.logicTree.LogicTreeBranch' to: Logic Tree Branch
Rupture Set:	Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations
Rupture Set:	Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations
Rupture Set:	Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags
Rupture Set:	Mapping available module with type: scratch.UCERF3.inversion.U3InversionTargetMFDs
Rupture Set:	Mapping available module with type: scratch.UCERF3.inversion.InversionTargetMFDs
Rupture Set:	Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.SectSlipRates
Rupture Set:	Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas
Rupture Set:	Lazily loading available module...
------------ LOADING ARCHIVE ------------
Archive: /tmp/u3_poly_associations16989743648660867586.zip
	Found available module 'Polygon Fault Association Manager' with path='null'
Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed
Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations$Precomputed
Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations
Mapping available module with type: org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations
Loaded 1 available top-level modules
---------- END LOADING ARCHIVE ----------
Lazily loading available module...
Building instance: org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed
Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations' to: Polygon Fault Grid Associations
Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations' to: Polygon Fault Grid Associations
Rupture Set:	Lazily loading available module...
Warning: parkfield not found...removed?
Warning: parkfield not found...removed?
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags$Precomputed' to: Modified Section Minimum Magnitudes
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags' to: Modified Section Minimum Magnitudes
Rupture Set:	Lazily loading available module...
Rupture Set:	Mapping module type 'scratch.UCERF3.inversion.U3InversionTargetMFDs' to: UCERF3 Inversion Target MFDs
Rupture Set:	Mapping module type 'scratch.UCERF3.inversion.InversionTargetMFDs' to: UCERF3 Inversion Target MFDs
Rupture Set:	Lazily loading available module...
java.lang.NullPointerException
Rupture Set:	Lazily loading available module...
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas$Default' to: Section Areas
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas' to: Section Areas
Rupture Set:	Removing module 'Tapered Slip Along Rupture' with type 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel$Tapered' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel$Tapered'
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel$Tapered' to: Tapered Slip Along Rupture
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SlipAlongRuptureModel' to: Tapered Slip Along Rupture
Rupture Set:	Getting copy of sub-module 'Rupture Average Slips' with updated parent
Rupture Set:	Removing module 'Rupture Average Slips' with type 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule$ModelBased' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule$ModelBased'
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule$ModelBased' to: Rupture Average Slips
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.AveSlipModule' to: Rupture Average Slips
Rupture Set:	Removing module 'Logic Tree Branch' with type 'scratch.UCERF3.logicTree.U3LogicTreeBranch' as it is assignable from 'scratch.UCERF3.logicTree.U3LogicTreeBranch'
Rupture Set:	Mapping module type 'scratch.UCERF3.logicTree.U3LogicTreeBranch' to: Logic Tree Branch
Rupture Set:	Mapping module type 'org.opensha.commons.logicTree.LogicTreeBranch' to: Logic Tree Branch
Rupture Set:	Removing module 'Polygon Fault Grid Associations' with type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed'
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations$Precomputed' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.PolygonFaultGridAssociations' to: Polygon Fault Grid Associations
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.FaultGridAssociations' to: Polygon Fault Grid Associations
Rupture Set:	Getting copy of sub-module 'Modified Section Minimum Magnitudes' with updated parent
Rupture Set:	Removing module 'Modified Section Minimum Magnitudes' with type 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags$Precomputed' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags$Precomputed'
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags$Precomputed' to: Modified Section Minimum Magnitudes
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ModSectMinMags' to: Modified Section Minimum Magnitudes
Rupture Set:	Getting copy of sub-module 'Section Slip Rates' with updated parent
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectSlipRates$Precomputed' to: Section Slip Rates
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectSlipRates' to: Section Slip Rates
Rupture Set:	Getting copy of sub-module 'Section Areas' with updated parent
Rupture Set:	Removing module 'Section Areas' with type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas$Default' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas'
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas$Precomputed' to: Section Areas
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SectAreas' to: Section Areas
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.InfoModule' to: Info
Rupture Set:	Getting copy of sub-module 'Plausibility Configuration' with updated parent
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.ruptures.plausibility.PlausibilityConfiguration' to: Plausibility Configuration
Rupture Set:	Getting copy of sub-module 'Single-Strand Cluster Ruptures' with updated parent
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.computeTargetSlipRates(InversionFaultSystemRupSet.java:485)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet$4.call(InversionFaultSystemRupSet.java:300)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet$4.call(InversionFaultSystemRupSet.java:1)
	at org.opensha.commons.util.modules.ModuleContainer.loadAvailableModule(ModuleContainer.java:398)
	at org.opensha.commons.util.modules.ModuleContainer.loadAllAvailableModules(ModuleContainer.java:383)
	at org.opensha.sha.earthquake.faultSysSolution.FaultSystemRupSet.init(FaultSystemRupSet.java:567)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.<init>(InversionFaultSystemRupSet.java:128)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemRuptSet.<init>(NZSHM22_InversionFaultSystemRuptSet.java:36)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemSolution.<init>(NZSHM22_InversionFaultSystemSolution.java:30)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemSolution.<init>(NZSHM22_InversionFaultSystemSolution.java:41)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:297)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_SubductionInversionRunner.main(NZSHM22_SubductionInversionRunner.java:105)
Rupture Set:	WARNING: failed to lazily load a module (see exception above)
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ClusterRuptures$SingleStranded' to: Single-Strand Cluster Ruptures
Rupture Set:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.ClusterRuptures' to: Single-Strand Cluster Ruptures
Rupture Set:	Getting copy of sub-module 'NZSHM22 Subduction Inversion Target MFDs' with updated parent
Exception in thread "main" java.lang.NullPointerException
	at scratch.UCERF3.inversion.U3InversionTargetMFDs.init(U3InversionTargetMFDs.java:191)
	at scratch.UCERF3.inversion.U3InversionTargetMFDs.<init>(U3InversionTargetMFDs.java:183)
	at scratch.UCERF3.inversion.U3InversionTargetMFDs.copy(U3InversionTargetMFDs.java:633)
	at scratch.UCERF3.inversion.U3InversionTargetMFDs.copy(U3InversionTargetMFDs.java:1)
	at org.opensha.commons.util.modules.ModuleContainer.checkCopySubModule(ModuleContainer.java:196)
	at org.opensha.commons.util.modules.ModuleContainer.addModule(ModuleContainer.java:158)
	at org.opensha.sha.earthquake.faultSysSolution.FaultSystemRupSet.init(FaultSystemRupSet.java:569)
	at scratch.UCERF3.inversion.InversionFaultSystemRupSet.<init>(InversionFaultSystemRupSet.java:128)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemRuptSet.<init>(NZSHM22_InversionFaultSystemRuptSet.java:36)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemSolution.<init>(NZSHM22_InversionFaultSystemSolution.java:30)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemSolution.<init>(NZSHM22_InversionFaultSystemSolution.java:41)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:297)
	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_SubductionInversionRunner.main(NZSHM22_SubductionInversionRunner.java:105)
```
