### ISSUE TITLE
Bug: Fix Hazard Background Seismicity

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#355]
When trying to refactor `NZSHM22_HazardCalculatorBuilder_IntegrationTest` by generating a `NZSHM22`-style solution instead of using a hard coded zip file, I was not able to see a difference in hazard with background seismicity enabled or disabled.

The expected behaviour is to see a difference in hazard when background is enabled (note: look up how polygons affect background).

The problem appears to be that our region is larger than the focalMech weight coverage.

```

FocalMech weights don't sum to 1: 0.0
java.lang.IllegalStateException: FocalMech weights don't sum to 1: 0.0
	at com.google.common.base.Preconditions.checkState(Preconditions.java:604)
	at org.opensha.sha.earthquake.PointSource.dataForMFDs(PointSource.java:651)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.buildData(PointSourceNshm.java:189)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:129)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:107)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:78)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:56)
	at org.opensha.sha.earthquake.faultSysSolution.modules.MFDGridSourceProvider$Abstract.getSource(MFDGridSourceProvider.java:372)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getOtherSource(BaseFaultSystemSolutionERF.java:810)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getSource(BaseFaultSystemSolutionERF.java:531)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.setAllNthRupRelatedArrays(BaseFaultSystemSolutionERF.java:896)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.updateForecast(BaseFaultSystemSolutionERF.java:357)
	at scratch.UCERF3.erf.FaultSystemSolutionERF.updateForecast(FaultSystemSolutionERF.java:352)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.loadERF(NZSHM22_HazardCalculatorBuilder.java:174)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.build(NZSHM22_HazardCalculatorBuilder.java:201)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder_IntegrationTest.hazardCalcTest(NZSHM22_HazardCalculatorBuilder_IntegrationTest.java:139)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy5.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:121)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)


```

**Comment by chrisdicaprio** [comment]
does the flag have an influence on the solution or just what's written for the bg seismicity?

**Comment by voj** [comment]
Once this is fixed, also re-enable hazard testing in the smoke tests workflow
