### ISSUE TITLE
Chore: Make hazard work with latest upstream

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#358]
When updating to the latest upstream commit 289e0aa9f777d997e10a73978e7192b6d7a27ffc, the hazard integration test fails with

```
java.lang.IllegalStateException: FocalMech weights don't sum to 1: 0.0
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
	at org.opensha.sha.earthquake.PointSource.dataForMFDs(PointSource.java:643)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.buildData(PointSourceNshm.java:189)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:129)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:107)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:78)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:56)
	at org.opensha.sha.earthquake.faultSysSolution.modules.MFDGridSourceProvider$Abstract.getSource(MFDGridSourceProvider.java:352)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getOtherSource(BaseFaultSystemSolutionERF.java:763)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getSource(BaseFaultSystemSolutionERF.java:489)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.setAllNthRupRelatedArrays(BaseFaultSystemSolutionERF.java:848)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.updateForecast(BaseFaultSystemSolutionERF.java:318)
	at scratch.UCERF3.erf.FaultSystemSolutionERF.updateForecast(FaultSystemSolutionERF.java:352)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.loadERF(NZSHM22_HazardCalculatorBuilder.java:176)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.build(NZSHM22_HazardCalculatorBuilder.java:203)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder_IntegrationTest.hazardCalcTest(NZSHM22_HazardCalculatorBuilder_IntegrationTest.java:38)
```

This is because `PointSource.dataForMFDs()` at line 643 checks that the weights for a location add up to 1. 

These weights are loaded at `NZSHM22_GridSourceGenerator.checkInitFocalMechGrids()`. The problem appears to be that the region we use is larger than the grids loaded from file. Weights for locations outside the file's grid are set to 0.

This is most likely not an issue because the region is larger than what we need. The precondition is a bit more strict than it needs to be.

Possible solutions:
- resize region to fit grid
- remove precondition

**Comment by voj** [comment]
Here are all the locations in the focalMechGrid files. Might not be easy to turn that into a rectangular region.

![image](https://github.com/user-attachments/assets/8b23fa89-b0d8-49cc-a3c1-a47604eacb41)

**Comment by voj** [comment]
Replaced with #359
