### ISSUE TITLE
Hazard calc is broken

### ISSUE THREAD

**Issue by voj** [GNS-Science/nzshm-opensha#359]
Note that we are currently not using OpenSHA hazard calculation, so this is not high priority for us. Our plan is to disable or delete our integration test until we actually decide that we need OpenSHA hazard calculation.

This ticket is to document the state of our research and hopefully get a few pointers from @kevinmilner while he hopefully still has the changes in his head. 

We have a hazard integration test that failed with https://github.com/opensha/opensha/commit/e871f94406368aa6384552adb70d7bbfe7091040 due to the result with included background seismicity being different. I guess this is explainable for a commit that changes distance calculation.

Our hazard calculation with included seismicity then completely broke with https://github.com/opensha/opensha/commit/71658fe114fd4f698c6e0dd938c06447f47a6509 and stays broken with the current OpenSHA HEAD:

```
FocalMech weights don't sum to 1: 0.0
java.lang.IllegalStateException: FocalMech weights don't sum to 1: 0.0
	at com.google.common.base.Preconditions.checkState(Preconditions.java:590)
	at org.opensha.sha.earthquake.PointSource.dataForMFDs(PointSource.java:643)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.buildData(PointSourceNshm.java:189)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:129)
	at org.opensha.sha.earthquake.rupForecastImpl.PointSourceNshm.<init>(PointSourceNshm.java:107)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:78)
	at scratch.UCERF3.griddedSeismicity.AbstractGridSourceProvider.buildSource(AbstractGridSourceProvider.java:56)
	at org.opensha.sha.earthquake.faultSysSolution.modules.MFDGridSourceProvider$Abstract.getSource(MFDGridSourceProvider.java:372)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getOtherSource(BaseFaultSystemSolutionERF.java:768)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.getSource(BaseFaultSystemSolutionERF.java:489)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.setAllNthRupRelatedArrays(BaseFaultSystemSolutionERF.java:853)
	at org.opensha.sha.earthquake.faultSysSolution.erf.BaseFaultSystemSolutionERF.updateForecast(BaseFaultSystemSolutionERF.java:318)
	at scratch.UCERF3.erf.FaultSystemSolutionERF.updateForecast(FaultSystemSolutionERF.java:352)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.loadERF(NZSHM22_HazardCalculatorBuilder.java:176)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.build(NZSHM22_HazardCalculatorBuilder.java:203)
	at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder_IntegrationTest.hazardCalcTest(NZSHM22_HazardCalculatorBuilder_IntegrationTest.java:38)
```

The problem occurs when we try to load background sesmicity. See below for a map of the `Region` that we use and all grid locations that we have focal mechs for. With recent OpenSHA refactors, focal mechs are required for each grid point.

A possible solution would be to create a `GriddenRegion` based only on the loaded focal mech points using [inferRegion](https://github.com/opensha/opensha/blob/4fd45e6a2456f24b2f98bf0996523c2d348cb7c8/src/main/java/org/opensha/commons/geo/GriddedRegion.java#L1362). This will then probably be needed to clip all other regions used like `TVZ` and `sansTVZ`. @kevinmilner do you think this would fix the issue?

![Screenshot 2024-12-12 115033](https://github.com/user-attachments/assets/79748ab7-7ef8-42df-b0f6-a6cd2811676e)

(focal mechs are [loaded here](https://github.com/GNS-Science/nzshm-opensha/blob/main/src/main/java/nz/cri/gns/NZSHM22/opensha/griddedSeismicity/NZSHM22_GridSourceGenerator.java#L271))

**Comment by kevinmilner** [comment]
Hi @voj, I added that check as part of a larger refactor of gridded seismicity codes. I think it's good to ensure that the focal mechanisms indeed sum to 1; it sounds like you were using that as a way to disable gridded seismicity for some nodes of your larger region.

I suggest either doing as you suggest, (creating a smaller GriddedRegion that includes only the nodes you need), or setting the focal mechanism weights to a dummy value but setting the MFDs to be empty for nodes that you wish to exclude.

**Comment by voj** [comment]
Thanks @kevinmilner !

**Comment by voj** [comment]
Won't fix until we actually need it. Using this issue for documentation. There is a link in the code to this ticket,
