### ISSUE TITLE
FIX: Error processing plot (skipping): SolMFDPlot on crustal solutions

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#37]
To reproduce , run new solution report on [SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=) to get this error: 
```{'file_id': 'SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=', 'file_path': '/home/chrisbc/DEV/GNS/opensha-new/AWS_S3_DATA/WORKING/downloads/SW52ZXJzaW9uU29sdXRpb246NjYzMy41RTZYMzU=/NZSHM22_InversionSolution-QXV0b21hdGlvblRhc2s6MjcxN3hkOUJT.zip', 'fault_model': 'CFM_0_9_SANSTVZ_D90'}
scheduling:  /home/chrisbc/DEV/GNS/opensha-new/AWS_S3_DATA/WORKING/task_1.sh
task count:  1
call_script with: /home/chrisbc/DEV/GNS/opensha-new/AWS_S3_DATA/WORKING/task_1.sh
Picked up JAVA_TOOL_OPTIONS: -Djava.awt.headless=true
Error processing plot (skipping): SolMFDPlot
java.lang.NullPointerException
	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SolMFDPlot.plot(SolMFDPlot.java:60)
	at org.opensha.sha.earthquake.faultSysSolution.reports.AbstractSolutionPlot.plot(AbstractSolutionPlot.java:22)
	at org.opensha.sha.earthquake.faultSysSolution.reports.ReportPageGen.generatePage(ReportPageGen.java:662)
	at nz.cri.gns.NZSHM22.util.NZSHM22_ReportPageGen.generatePage(NZSHM22_ReportPageGen.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.base/java.lang.Thread.run(Thread.java:829)
worker count:  4
Done! in 245.182637 secs
```

**Comment by voj** [comment]
Fixed by properly writing MFD constraints into the solution
