### ISSUE TITLE
BUG: MFDPlotBuilder exception

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#83]
Currenlty can't build named plots ....

on branch `feature/78-regional-sub-seismo` of **nzshm-opensha**
```

  | 2021-11-22T11:12:40.182+13:00 | File "/app/nzshm-runzi/runzi/execute/inversion_diags_report_task.py", line 142, in <module>
-- | -- | --
  | 2021-11-22T11:12:40.182+13:00 | task.run(**config)
  | 2021-11-22T11:12:40.182+13:00 | File "/app/nzshm-runzi/runzi/execute/inversion_diags_report_task.py", line 55, in run
  | 2021-11-22T11:12:40.182+13:00 | self.build_mfd_plots(task_arguments, job_arguments)
  | 2021-11-22T11:12:40.182+13:00 | File "/app/nzshm-runzi/runzi/execute/inversion_diags_report_task.py", line 106, in build_mfd_plots
  | 2021-11-22T11:12:40.182+13:00 | plot_builder.plot()
  | 2021-11-22T11:12:40.182+13:00 | File "/usr/lib/python3.9/site-packages/py4j/java_gateway.py", line 1304, in __call__
  | 2021-11-22T11:12:40.183+13:00 | return_value = get_return_value(
  | 2021-11-22T11:12:40.183+13:00 | File "/usr/lib/python3.9/site-packages/py4j/protocol.py", line 326, in get_return_value
  | 2021-11-22T11:12:40.183+13:00 | raise Py4JJavaError(
  | 2021-11-22T11:12:40.184+13:00 | py4j.protocol.Py4JJavaError: An error occurred while calling o5.plot.
  | 2021-11-22T11:12:40.184+13:00 | : java.lang.NullPointerException
  | 2021-11-22T11:12:40.184+13:00 | at scratch.UCERF3.inversion.InversionFaultSystemSolution.getFinalSubSeismoOnFaultMFD_List(InversionFaultSystemSolution.java:712)
  | 2021-11-22T11:12:40.184+13:00 | at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_InversionFaultSystemSolution.getFinalSubSeismoOnFaultMFDForSects(NZSHM22_InversionFaultSystemSolution.java:125)
  | 2021-11-22T11:12:40.184+13:00 | at nz.cri.gns.NZSHM22.util.MFDPlot.writeParentSectionMFDPlots(MFDPlot.java:95)
  | 2021-11-22T11:12:40.184+13:00 | at nz.cri.gns.NZSHM22.opensha.util.MFDPlotBuilder.plot(MFDPlotBuilder.java:62)
  | 2021-11-22T11:12:40.184+13:00 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | 2021-11-22T11:12:40.184+13:00 | at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
```

**Comment by chrisbc** [comment]
with upstream at `2c6602a` and nzhsm-opensha at `tags/feature/78-regional-sub-seismo' 

```
Building instance: org.opensha.sha.earthquake.faultSysSolution.modules.SubSeismoOnFaultMFDs
Solution:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SubSeismoOnFaultMFDs' to: Sub-Seismogenic On-Fault MFDs
Solution:	Mapping module type 'scratch.UCERF3.simulatedAnnealing.completion.AnnealingProgress' to: Annealing Progress
Solution:	Removing available module with type 'org.opensha.sha.earthquake.faultSysSolution.modules.SubSeismoOnFaultMFDs' as it is assignable from 'org.opensha.sha.earthquake.faultSysSolution.modules.SubSeismoOnFaultMFDs'
Solution:	Mapping module type 'org.opensha.sha.earthquake.faultSysSolution.modules.SubSeismoOnFaultMFDs' to: Sub-Seismogenic On-Fault MFDs
Solution:	Removing available module with type 'scratch.UCERF3.griddedSeismicity.GridSourceProvider' as it is assignable from 'scratch.UCERF3.griddedSeismicity.GridSourceProvider'
Solution:	Mapping available module with type: scratch.UCERF3.griddedSeismicity.GridSourceProvider
Exception in thread "main" java.lang.NullPointerException
	at nz.cri.gns.NZSHM22.opensha.util.MFDPlotBuilder.plot(MFDPlotBuilder.java:52)
	at nz.cri.gns.NZSHM22.opensha.util.MFDPlotBuilder.main(MFDPlotBuilder.java:78)
```

**Comment by chrisbc** [comment]
resolved in latest release
