### ISSUE TITLE
Bug: opensha FULL sub-reports raise exceptions 

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#88]
Done when:
 - [ ] sub-report failures in **SectBValuePlot.estBValue** on certain parent faults are fixed

Related:
 - see https://github.com/GNS-Science/nzshm-runzi/issues/46 for details of the in improved exception handling 
 
Contest 
see below a log snippet w java traceback from AWS job (Fargate-runzi-opensha-JD/default/3e2e5af71b4f4cb7b57e0e9ae733b51d) 

This was run with [SW52ZXJzaW9uU29sdXRpb246MTU0NjUuMGR4VVpN](http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246MTU0NjUuMGR4VVpN)

using python gateway ...

```
        self._page_gen\
            .setName(f"Solution Diagnostics: {ta['file_id']}")\
            .setSolution(ta['file_path'])\
            .setOutputPath(str(solution_report_folder))\
            .setPlotLevel(job_arguments['build_report_level'])\
            .setFillSurfaces(True)\
            .generatePage()
```

where job_arguments['build_report_level']) = 'FULL'

Based on AWS log file and what was pushed to S3 it appears that only 5 parent_fault reports succeeded.

  | Name | Type | Last modified | Size | Storage class
  | -- | -- | -- | -- | -- | --
  | Calypso_2/ | Folder | - | - | -
  | Ohae_3/ | Folder | - | - | -
  | Pakarae/ | Folder | - | - | -
  | Paritu_West/ | Folder | - | - | -
  | Totara_Saddle/

```1637826110526,downloaded input file: /WORKING/downloads/SW52ZXJzaW9uU29sdXRpb246MTU0NjUuMGR4VVpN/NZSHM22_InversionSolution-QXV0b21hdGlvblRhc2s6NTQxMjJFS0hn.zip <_io.BufferedWriter name='/WORKING/downloads/SW52ZXJzaW9uU29sdXRpb246MTU0NjUuMGR4VVpN/NZSHM22_InversionSolution-QXV0b21hdGlvblRhc2s6NTQxMjJFS0hn.zip'>
1637826178538,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 0' to 'Hawke Bay 4, Subsection 0 (2)'"
1637826178538,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 1' to 'Hawke Bay 4, Subsection 1 (2)'"
1637826322573,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 0' to 'Hawke Bay 4, Subsection 0 (2)'"
1637826322573,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 1' to 'Hawke Bay 4, Subsection 1 (2)'"
1637826364065,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 0' to 'Hawke Bay 4, Subsection 0 (2)'"
1637826364065,"WARNING: duplicate fault section name detected, changing 'Hawke Bay 4, Subsection 1' to 'Hawke Bay 4, Subsection 1 (2)'"
1637826592515,Error processing plot (skipping): SectBValuePlot
1637826592515,java.lang.IllegalStateException
1637826592516,	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estBValue(SectBValuePlot.java:401)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estBValue(SectBValuePlot.java:320)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estSectBValues(SectBValuePlot.java:243)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.plot(SectBValuePlot.java:88)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.AbstractSolutionPlot.plot(AbstractSolutionPlot.java:22)
1637826592516,	at org.opensha.sha.earthquake.faultSysSolution.reports.ReportPageGen.generatePage(ReportPageGen.java:765)
1637826592516,	at nz.cri.gns.NZSHM22.util.NZSHM22_ReportPageGen.generatePage(NZSHM22_ReportPageGen.java:99)
1637826592516,	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1637826592516,	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
1637826592516,	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
1637826592516,	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
1637826592516,	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
1637826592516,	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
1637826592516,	at py4j.Gateway.invoke(Gateway.java:282)
1637826592516,	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
1637826592516,	at py4j.commands.CallCommand.execute(CallCommand.java:79)
1637826592516,	at py4j.GatewayConnection.run(GatewayConnection.java:238)
1637826592516,	at java.base/java.lang.Thread.run(Unknown Source)
1637826979623,Error processing plot (skipping): SectBySectDetailPlots
1637826979623,java.lang.IllegalStateException
1637826979623,	at com.google.common.base.Preconditions.checkState(Preconditions.java:492)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estBValue(SectBValuePlot.java:401)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estBValue(SectBValuePlot.java:320)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots.buildBValPlot(SectBySectDetailPlots.java:1949)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots.getAlongStrikeLines(SectBySectDetailPlots.java:1242)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots.buildSectionPage(SectBySectDetailPlots.java:390)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots$SectPageCallable.call(SectBySectDetailPlots.java:269)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots$SectPageCallable.call(SectBySectDetailPlots.java:245)
1637826979623,	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBySectDetailPlots.plot(SectBySectDetailPlots.java:187)
1637826979624,	at org.opensha.sha.earthquake.faultSysSolution.reports.ReportPageGen.generatePage(ReportPageGen.java:765)
1637826979624,	at nz.cri.gns.NZSHM22.util.NZSHM22_ReportPageGen.generatePage(NZSHM22_ReportPageGen.java:99)
1637826979624,	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
1637826979624,	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
1637826979624,	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
1637826979624,	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
1637826979624,	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
1637826979624,	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
1637826979624,	at py4j.Gateway.invoke(Gateway.java:282)
1637826979624,	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
1637826979624,	at py4j.commands.CallCommand.execute(CallCommand.java:79)
1637826979624,	at py4j.GatewayConnection.run(GatewayConnection.java:238)
1637826979624,	at java.base/java.lang.Thread.run(Unknown Source)
1637826979653,INFO:root:Beginning bucket upload... to nzshm22-static-reports/opensha/DATA//SW52ZXJzaW9uU29sdXRpb246MTU0NjUuMGR4VVpN
```

**Comment by chrisbc** [comment]
@voj I have updated this ticket to cover just the SectBValuePlot.estBValue issue, which is (I think) still happening.

**Comment by voj** [comment]
With Kevin's changes in https://github.com/opensha/opensha/commit/1b875d783915b3aec3bb4723677203f2f9003e02 there's now a new exception:
```
Error processing plot (skipping): SectBValuePlot
java.lang.IndexOutOfBoundsException: no point at index -1
	at org.opensha.commons.data.function.EvenlyDiscretizedFunc.getX(EvenlyDiscretizedFunc.java:276)
	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot$BValEstimate.<init>(SectBValuePlot.java:354)
	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estBValue(SectBValuePlot.java:322)
	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.estSectBValues(SectBValuePlot.java:243)
	at org.opensha.sha.earthquake.faultSysSolution.reports.plots.SectBValuePlot.plot(SectBValuePlot.java:88)
	at org.opensha.sha.earthquake.faultSysSolution.reports.AbstractSolutionPlot.plot(AbstractSolutionPlot.java:22)
	at org.opensha.sha.earthquake.faultSysSolution.reports.ReportPageGen.generatePage(ReportPageGen.java:765)
	at nz.cri.gns.NZSHM22.util.NZSHM22_ReportPageGen.generatePage(NZSHM22_ReportPageGen.java:99)
	at nz.cri.gns.NZSHM22.util.NZSHM22_ReportPageGen.main(NZSHM22_ReportPageGen.java:112)
```

**Comment by voj** [comment]
I've created an upstream issue https://github.com/opensha/opensha/issues/68

**Comment by voj** [comment]
Waiting for PR https://github.com/opensha/opensha/pull/69

**Comment by voj** [comment]
fixed upstream
