### ISSUE TITLE
Bug: Inversion failure on new Coulomb Rupture set

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#91]
trace:

```
2021-11-29T09:11:58.609+13:00	: java.lang.RuntimeException: Bad MFD for section: 970 Marlborough Slope 9, Subsection 0 gridSeisUtils.pdfValForSection(s) = NaN mMax = 6.949999999999999
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.analysis.NZSHM22_FaultSystemRupSetCalc.getCharSubSeismoOnFaultMFD_forEachSection(NZSHM22_FaultSystemRupSetCalc.java:133)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs$RegionalTargetMFDs.init(NZSHM22_CrustalInversionTargetMFDs.java:210)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs$RegionalTargetMFDs.<init>(NZSHM22_CrustalInversionTargetMFDs.java:118)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs.init(NZSHM22_CrustalInversionTargetMFDs.java:271)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionTargetMFDs.<init>(NZSHM22_CrustalInversionTargetMFDs.java:85)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionConfiguration.forModel(NZSHM22_CrustalInversionConfiguration.java:129)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.configure(NZSHM22_CrustalInversionRunner.java:167)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.configure(NZSHM22_CrustalInversionRunner.java:27)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_AbstractInversionRunner.runInversion(NZSHM22_AbstractInversionRunner.java:403)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.inversion.NZSHM22_CrustalInversionRunner.runInversion(NZSHM22_CrustalInversionRunner.java:211)
2021-11-29T09:11:58.609+13:00	at nz.cri.gns.NZSHM22.opensha.util.NZSHM22_PythonGateway$CachedCrustalInversionRunner.runInversion(NZSHM22_PythonGateway.java:296)
```

Using new rupture set  http://simple-toshi-ui.s3-website-ap-southeast-2.amazonaws.com/FileDetail/RmlsZToxNTQ3Ni4wZVBZUHU=

on commit/branch

```
chrisbc@tryharder-ubuntu:~/DEV/GNS/opensha-modular/nzshm-opensha$ git log -1
commit c6beef079bda300a410ab3999b4ade76e0cf8304 (HEAD -> feature/90_add_updated_crustal_D90_fault_models, origin/feature/90_add_updated_crustal_D90_fault_models)
Author: Chris Chamberlain <chrisbc@artisan.co.nz>
Date:   Sat Nov 27 18:18:32 2021 +1300

    added new cfm_0_9a_* for d90; created new FaultsByNameAlt;
```

**Configs:**

```
max_sections: 2000, 
fault_model: CFM_0_9A_SANSTVZ_D90, 
min_sub_sects_per_parent: 2, 
min_sub_sections: 2, 
max_jump_distance: 15, 
adaptive_min_distance: 6, 
thinning_factor: 0, 
scaling_relationship: TMG_CRU_2017
```

**Comment by voj** [comment]
Will be fixed upstream https://github.com/opensha/opensha/issues/62

**Comment by voj** [comment]
Fixed upstream
