### ISSUE TITLE
Bug: Hazard calculator error

### ISSUE THREAD

**Issue by chrisbc** [GNS-Science/nzshm-opensha#95]
**To Reproduce:**

call hazard (via py4j gateway) using test inversion solution http://simple-toshi-ui-test.s3-website-ap-southeast-2.amazonaws.com/InversionSolution/SW52ZXJzaW9uU29sdXRpb246Mjk2MS4wREtva2Q=

gitrefs:

**opensha (GNS):** @ da915e2201dd4bd95214520f415908d95ad494dc
**nzshm-opensha:** @ 25fd82e0b338bec285dcb2aa8b3a43c6d8970066 

```Traceback (most recent call last):
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/runzi/automation/scaling/inversion_hazard_report_task.py", line 228, in <module>
    task.run(**config)
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/runzi/automation/scaling/inversion_hazard_report_task.py", line 65, in run
    calculator = self._hazard_builder.build()
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/lib/python3.8/site-packages/py4j/java_gateway.py", line 1304, in __call__
    return_value = get_return_value(
  File "/home/chrisbc/DEV/GNS/opensha-modular/nzshm-runzi/lib/python3.8/site-packages/py4j/protocol.py", line 326, in get_return_value
    raise Py4JJavaError(
py4j.protocol.Py4JJavaError: An error occurred while calling o0.build.
: java.lang.NullPointerException
        at scratch.UCERF3.inversion.InversionFaultSystemSolution.getFinalTrulyOffFaultMFD(InversionFaultSystemSolution.java:802)
        at scratch.UCERF3.griddedSeismicity.UCERF3_GridSourceGenerator.<init>(UCERF3_GridSourceGenerator.java:109)
        at scratch.UCERF3.griddedSeismicity.UCERF3_GridSourceGenerator.<init>(UCERF3_GridSourceGenerator.java:83)
        at scratch.UCERF3.inversion.InversionFaultSystemSolution.getGridSourceProvider(InversionFaultSystemSolution.java:859)
        at scratch.UCERF3.erf.FaultSystemSolutionERF.initOtherSources(FaultSystemSolutionERF.java:1025)
        at scratch.UCERF3.erf.FaultSystemSolutionERF.updateForecast(FaultSystemSolutionERF.java:412)
        at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.loadERF(NZSHM22_HazardCalculatorBuilder.java:133)
        at nz.cri.gns.NZSHM22.opensha.hazard.NZSHM22_HazardCalculatorBuilder.build(NZSHM22_HazardCalculatorBuilder.java:158)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by voj** [comment]
I had a look at what needs to happen to make hazard work and it goes beyond a bug fix. Hazard has not yet been updated for modular solutions, for NZ LogicTreeBranches, etc

**Comment by voj** [comment]
@chrisbc I have a working version that can calculate hazard for modular and pre-modular solutions. It was much easier than I had thought.

There are several problems with it:
- I had to make decisions on how to re-implement U3 methods, we need to verify that my choices are correct.
- `NZSHM22_GridSourceGenerator` uses a NZ-wide SpatialSeisPDF, and totalMgt5_Rate is ignored
- We still rely on U3 classes
